exports.POCHTA_YANGI = "YANGI";
exports.POCHTA_YULDA = "YO`LDA";
exports.POCHTA_YETIB_BORDI = "YETIB BORDI";
exports.POCHTA_YETIB_BORMADI = "YETIB BORMADI";
exports.POCHTA_OTKAZ_YANGI = "OTKAZ YANGI";
exports.POCHTA_OTKAZ_YULDA = "OTKAZ YO`LDA";
exports.POCHTA_OTKAZ_YETDI = "OTKAZ BORDI";
exports.POCHTA_OTKAZ_BORMADI = "OTKAZ BORMADI";
