exports.POST_NEW = "NEW";
exports.POST_DELIVERING = "DELIVERING";
exports.POST_DELIVERED = "DELIVERED";
exports.POST_NOT_DELIVERED = "NOT_DELIVERED";
exports.POST_REJECTED_NEW = "REJECTED_NEW";
exports.POST_REJECTED_DELIVERING = "REJECTED_DELIVERING";
exports.POST_REJECTED_DELIVERED = "REJECTED_DELIVERED";
exports.POST_REJECTED_NOT_DELIVERED = "REJECTED_NOT_DELIVERED";
